### ISSUE TITLE
右下角导航序号

### ISSUE THREAD

**Issue by YoungTakhin** [ikeq/hexo-theme-inside#132]
可否设置一个选项关掉右下角导航的序号，或者为post文章的标题渲染序号，我在markdown中为post文章标题加了序号，结果右下角的导航也渲染出了多余的序号，简直逼死强迫症啊

**Comment by ikeq** [comment]
设置 toc.index 为 `false`
```yml
toc:
  # 最多显示几层目录，最多 4 层，缺省值 `3`
  depth:
  # 是否显示标号，如 1.1、1.2，默认显示，设置为 false 可隐藏。
  index: false
```
https://blog.oniuo.com/theme-inside/docs/content-addons#toc
