### ISSUE TITLE
点击上/下一页后，插件在新页面未生效

### ISSUE THREAD

**Issue by fiteen** [ikeq/hexo-theme-inside#194]
### 问题一

- 问题描述：如题。通过标题进入当前网页，代码复制功能有效；但通过上/下一页进入新的一篇文章时，插件无效。

- 相关代码：
```
plugins:
  # 代码复制
  - position: [post, page]
    template: |
      <script type="text/javascript" src="//cdn.jsdelivr.net/npm/clipboard@2.0.4/dist/clipboard.js"></script>
      <script type="text/javascript" src="//cdn.jsdelivr.net/gh/fiteen/fiteen.github.io@v0.1.0/clipboard-use.js"></script>
      <link href="//cdn.jsdelivr.net/gh/fiteen/fiteen.github.io@v0.1.1/clipboard.css" rel="stylesheet">
      <link href="lib/font-awesome/css/font-awesome.min.css" rel="stylesheet">
```
- 效果：例如点击这篇[文章](https://blog.fiteen.top/2020/ios-runtime)时，代码块中能显示复制按钮，但点击下一篇时，就无法显示了。

### 问题二

- 问题描述：文章 markdown 中插入代码折叠，点击折叠框时周围会出现一圈蓝色边框。

- 相关代码：

```
<details>
  <summary>Summary</summary>
  <p>Content<p>
</details>
```

对前端不是很熟悉，或许要加一下 `:focus {outline:none;}` 样式？

**补充**：点击搜索框也有这个情况，貌似是主题升级到 v2.6.1 之后出现的。

**Comment by ikeq** [comment]
### 问题 1：

因为是异步渲染，页面不会刷新，解决方案就是要么使用 web components（插入和移除 dom 都有完整的生命周期回调），要么事件委托，以你[这里](https://blog.fiteen.top/2020/hexo-theme-inside-plugin)的代码为例，

```yml
plugins:
  # 插入依赖 libs
  - //cdn.jsdelivr.net/npm/clipboard@2.0.4/dist/clipboard.js
  - //cdn.jsdelivr.net/gh/fiteen/fiteen.github.io@v0.1.0/clipboard-use.js
  - //cdn.jsdelivr.net/gh/fiteen/fiteen.github.io@v0.1.1/clipboard.css
  - lib/font-awesome/css/font-awesome.min.css

  # 插入事件委托代码
  - tag: script
    code: |
        $('main').on('click', '.btn-copy', function() {
          // 需要直接执行 copy 动作
        })

  # 在每一篇文章渲染完毕后，插入复制代码的小 icon
  - position: [post, page]
  - template: |
      $(".highlight .code pre").before('<a class="btn-copy fa fa-clipboard"></a>');
```

### 问题 2：

之前考虑到可访问性的问题故把 `:focus { outline: none }` 删掉了，后面优化一下～

**Comment by fiteen** [comment]
@ikeq 感谢解答。

不过我按照这个上面介绍的方式试了一下，点击上/下一页后复制 icon 并未重新渲染出来。

下面是我的配置代码，能否帮忙看一下问题在哪里。

```yaml
plugins:
  # 插入依赖 libs
  - //cdn.jsdelivr.net/gh/fiteen/fiteen.github.io@v0.1.1/clipboard.css
  - //cdn.jsdelivr.net/npm/clipboard@2.0.4/dist/clipboard.js
  - lib/font-awesome/css/font-awesome.min.css

  # 插入事件委托代码
  - tag: script
    type: text/javascript
    code: |
      $(function() {
        $('main').on('click', '.btn-copy', function() {
          new ClipboardJS('.btn-copy', {
            target: function (trigger) {
              return trigger.nextElementSibling;
            }
          });
        })
      })

  # 在每一篇文章渲染完毕后，插入复制代码的小 icon     
  - position: [post, page]
    template: |
      <script type="text/javascript">
        console.log("--add icon--");
        $(".highlight .code pre").before('<i class="btn-copy fa fa-clipboard"></i>');
      </script>
```

**Comment by ikeq** [comment]
@fiteen `console.log("--add icon--")` 是否有执行？

**Comment by fiteen** [comment]
@ikeq 只有第一次进入才会执行，下一页的时候没有。

**Comment by ikeq** [comment]
我试了一下，是主题的问题，在修复之前，你可以试试这样写：
```css
.highlight .code pre:after {
  padding: 2px;
  position: absolute;
  right: 5px;
  top: 5px;
  font: normal normal normal 14px/1 FontAwesome;
  cursor: pointer;
}
.highlight:hover .code pre:after {
  content: "\f0ea";
}
```

```yml
plugins:
  # 插入依赖 libs
  - //cdn.jsdelivr.net/gh/fiteen/fiteen.github.io@v0.1.1/clipboard.css
  - //cdn.jsdelivr.net/npm/clipboard@2.0.4/dist/clipboard.js
  - lib/font-awesome/css/font-awesome.min.css

  # 插入事件委托代码
  - tag: script
    type: text/javascript
    code: |
      $(function() {
        $('main').on('click', '.highlight .code pre', function() {
          console.log("--add icon--");
        })
      })
