### ISSUE TITLE
how so I add a theme Palette similar to the one running on your blog site?

### ISSUE THREAD

**Issue by mediocre-mayda** [ikeq/hexo-theme-inside#225]
![image](https://user-images.githubusercontent.com/37749765/84528256-a12d3380-acdf-11ea-81b2-4a6be7518e67.png)

**Comment by sahmura** [comment]
I'm waiting for the answer

**Comment by ikeq** [comment]
```yml
plugins:
  - //blog.oniuo.com/theme.js
  - //blog.oniuo.com/wc.cc9a2092fece1d80bf3b.js
  - position: sidebar
    template: <is-palette2></is-palette2>
```

That will work.

**Comment by mediocre-mayda** [comment]
thanks a lot @ikeq 
can we get the unminified version of this js, I really would love full customization to this color pallete

**Comment by ikeq** [comment]
Sure, once I have time ❤️

**Comment by ikeq** [comment]
> ```yaml
> plugins:
>   - //blog.oniuo.com/theme.js
>   - //blog.oniuo.com/wc.cc9a2092fece1d80bf3b.js
>   - position: sidebar
>     template: <is-palette2></is-palette2>
> ```
> 
> That will work.

update:
since the lastest version

```yaml
plugins:
  - palette
  - position: sidebar
    template: |
      <is-palette palette="#673ab7,#3f51b5,#2196f3,#009688,#4caf50,#ff9800,#ff5722,#795548,#607D8B,#2a2b33"></is-palette>
```
