### ISSUE TITLE
gittalk 支持

### ISSUE THREAD

**Issue by xuxusheng** [ikeq/hexo-theme-inside#230]
请问考虑下集成 gittalk 评论不：https://github.com/gitalk/gitalk

**Comment by xuxusheng** [comment]
演示：https://gitalk.github.io/

**Comment by ikeq** [comment]
支持呀，试试下面的代码：
```yml
plugins:
  - https://unpkg.com/gitalk/dist/gitalk.css
  - https://unpkg.com/gitalk/dist/gitalk.min.js
  - position: comments
     template: |
       <div id="gitalk-container"></div>
       new Gitalk({
         clientID: 'GitHub Application Client ID',
         clientSecret: 'GitHub Application Client Secret',
         repo: 'GitHub repo',
         owner: 'GitHub repo owner',
         admin: [],
         id: location.pathname, 
         distractionFreeMode: false
       }).render('gitalk-container')
```
