### ISSUE TITLE
如何打开调色板并且正常更换网站背景？

### ISSUE THREAD

**Issue by BluerAngala** [ikeq/hexo-theme-inside#258]
![image](https://user-images.githubusercontent.com/49632180/103442459-4ebe5f00-4c91-11eb-947a-dcbc2c6da540.png)

**Comment by ikeq** [comment]
```yaml
plugins:
   - palette
   - position: sidebar
       template: |
         <is-palette palette="#673ab7,#3f51b5,#2196f3,#009688,#4caf50,#ff9800,#ff5722,#795548" col="4"></is-palette>
```
