### ISSUE TITLE
How to use Disqusjs as my comments plugin

### ISSUE THREAD

**Issue by DioPong** [ikeq/hexo-theme-inside#286]
I did follow your doc, follow [Djsqusjs's guide](<https://github.com/SukkaW/DisqusJS>) and add it to `_config.inside.yml`, but it can't be shown. I don't know what to do, can you help?

Here is my plugin config:

```yml
plugins:
  - //cdn.jsdelivr.net/npm/disqusjs@1.3/dist/disqusjs.css
  - //cdn.jsdelivr.net/npm/disqusjs@1.3/dist/disqus.js
  - position: comments
    template: |
      <div id="disqus_thread"></div>
      <script>
        var dsqjs = new DisqusJS({
          shortname: diopong,
          siteName: '',
          identifier: document.location.origin + document.location.pathname + document.location.search,
          url: document.location.origin + document.location.pathname + document.location.search,
          title: '',
          api: https://disqus.skk.moe/disqus/,
          apikey: xxxxxxxxxx,
          nesting: 3,
          admin: '',
          adminLabel: ''
        });
      </script>
```

And here is what my blog looks like.

![image](https://user-images.githubusercontent.com/48322394/125220163-d2b86a00-e2f8-11eb-89d7-5ad554b69608.png)

I'll appreciate it if you help!   :)

**Comment by ikeq** [comment]
version 2.7.0-beta.18

**Comment by DioPong** [comment]
> version 2.7.0-beta.18 ?

Yes, I installed hexo-theme-inside@2.7.0-beta.18

![image](https://user-images.githubusercontent.com/48322394/125221393-c208f380-e2fa-11eb-9634-35384d314c1f.png)

🎈 What else should I provide :P

**Comment by ikeq** [comment]
any error printed in console?

**Comment by DioPong** [comment]
Oh, I get it! After checking error in console, I found an error occured in `api: https://disqus.skk.moe/disqus/,`. In the plugin config, I should use inverted comma to quote all my disqusjs's String value.

When I add inverted comma in it, nothing go wrong anymore. That's my fault.

```yml
plugins:
  - //cdn.jsdelivr.net/npm/disqusjs@1.3/dist/disqusjs.css
  - //cdn.jsdelivr.net/npm/disqusjs@1.3/dist/disqus.js
  - position: comments
    template: |
      <div id="disqus_thread"></div>
      <script>
        var dsqjs = new DisqusJS({
          shortname: 'diopong',
          siteName: '',
          identifier: 'document.location.origin + document.location.pathname + document.location.search',
          url: 'document.location.origin + document.location.pathname + document.location.search',
          title: '',
          api: 'https://disqus.skk.moe/disqus/',
          apikey: '{My API}',
          nesting: 3,
          admin: '',
          adminLabel: ''
        });
      </script>
```
