### ISSUE TITLE
How to display code block?

### ISSUE THREAD

**Issue by nhiennn-miichisoft** [ikeq/hexo-theme-inside#296]
Version: 2.7.0-beta.21

I try both markdown and tag syntax:

![image](https://user-images.githubusercontent.com/85109298/136577898-3374da52-d00a-439e-a7c4-f0133cffc1f1.png)

But content display have no style

![image](https://user-images.githubusercontent.com/85109298/136577967-8b71604e-03a7-48ed-a8b3-5ae5585f350c.png)

Here is config:

![image](https://user-images.githubusercontent.com/85109298/136578227-d6a4e6de-6162-4c06-a251-74d378c51db7.png)

I try to disable one of them: highlight & prismjs but still not work

What I miss?

**Comment by ikeq** [comment]
I tested golang and php and both worked as expected, here is my config:

```yml
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:
```

Note prismjs is not supported yet.
