### ISSUE TITLE
主题配置中font服务似乎挂掉了

### ISSUE THREAD

**Issue by hrQAQ** [ikeq/hexo-theme-inside#320]
主题配置中外观设置appearance: font: 部分摘录如下

``` yml
# 字体设置
  font:
    # 字体 CSS 文件的 URL
    url: //fonts.googleapis.com/css?family=Baloo+Bhaijaan|Inconsolata|Josefin+Sans|Montserrat
```

这个字体css文件部分摘录如下

``` css
/* arabic */
@font-face {
  font-family: 'Baloo Bhaijaan';
  font-style: normal;
  font-weight: 400;
  src: url(https://fonts.gstatic.com/s/baloobhaijaan/v16/RWmRoKCU5fcqq8fOWNzFLqSjx7EALGRTCw.woff2) format('woff2');
  unicode-range: U+0600-06FF, U+200C-200E, U+2010-2011, U+204F, U+2E41, U+FB50-FDFF, U+FE80-FEFC;
}
```

可以看到，这个css文件使用了https://fonts.gstatic.com/s/baloobhaijaan/v16/RWmRoKCU5fcqq8fOWNzFLqSjx7EALGRTCw.woff2 的内容，但是这个链接似乎是挂掉了？在我的机器上没有办法访问到这个资源（已科学上网），访问失败的图片截图如下：

![image](https://user-images.githubusercontent.com/89020793/188357209-7c0f4e88-2948-448b-8d90-debffad24e4d.png)
