### ISSUE TITLE
Customize the css class for the thumbnail img

### ISSUE THREAD

**Issue by jason19970210-senao** [ikeq/hexo-theme-inside#325]
Mentioned in subject, the current config for the `img` class in css just like below:
```css
img {
  max-width: 100%
}
``` 

and for my case, I would like to display the img thumbnails with the following:
```css
img {
    height: 250px;
    object-fit: cover;
}
```

Nice to have this customization for our own blog style !!
Appreciate!!
