### ISSUE TITLE
請問怎麼在文章加入觀看次數

### ISSUE THREAD

**Issue by WU898989** [ikeq/hexo-theme-inside#344]
![image](https://github.com/user-attachments/assets/fa77580b-4e4a-4a54-a374-7c609547654b)

**Comment by ikeq** [comment]
抱歉未及时回复。

观看次数需要借助主题 plugin 的能力在文章详情的场景执行脚本实现上报和展示，示例如下：

脚本
```html
<!-- post-log.html -->
<script>
  // 1. 上报当前路由 PV，需自行实现相关接口
  fetch(`xxx/pv?id=${location.pathname}`);

  // 2. 读取当前路由 PV，需自行实现相关接口
  fetch(`xxx/get/pv?id=${location.pathname}`)
    .then(res => res.json())
    .then(count => {
      // 3. 展示，固定写法，只需修改 count 部分的逻辑
      document.dispatchEvent(
        new CustomEvent('inside', {
          detail: {
            type: 'pv',
            data: {
              // 如 'post/inside-theme-showcase': 999
              [location.pathname.substring(1)]: count
            },
          },
        })
      );
    });
</script>
```

主题插件配置
```yml
# _config.inside.yml
plugins:
  - position: [post, 'page']
    template: post-log.html
```
